version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.3

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - run:
          command: echo 'export APP_KEY=base64:ArlPYBNoNt2nqbHSN5njDiBxD82a+wF90efU/Yf3Hr8=' >> $BASH_ENV

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # run tests
      - run: ./vendor/bin/phpunit
